var = input('Digite algo: ')
print ('O tipo primitivo dessa variavel é: ', (type(var)))
print('"{}" é numerico?'.format(var), var.isalnum())
print('"{}" é alfa? '.format(var), var.isalpha())
print('"{}" é decimal? '.format(var), var.isdecimal())
print('"{}" é um digito? '.format(var), var.isdigit())
print('"{}" é identificador? '.format(var), var.isidentifier())
print('"{}" está tudo em caixa baixa? '.format(var), var.islower())
print('"{}" é imprimivel? '.format(var), var.isprintable() )
print('"{}" está tudo em caixa alta? '.format(var), var.isupper())
print('"{}" é um espaço? '.format(var), var.isspace())